export const NEXT_SLIDE = 'NEXT_SLIDE';
export const ADD_BLOCK  = 'ADD_BLOCK';
export const HIGHLIGHT_BLOCKS = 'HIGHLIGHT_BLOCKS';
export const REMOVE_HIGHLIGHTS = 'REMOVE_HIGHLIGHTS';
export const HIGHLIGHT_BLOCK_WITH_INDEX = 'HIGHLIGHT_BLOCK_WITH_INDEX';