export const FOLLOW 					= 'FOLLOW';
export const REQUEST_PARK_IMGS 			= 'REQUEST_PARK_IMGS';
export const RECEIVE_PARK_IMGS 			= 'RECEIVE_PARK_IMGS';

export const RECEIVE_API_KEY 			= 'RECEIVE_API_KEY';
export const INVALIDATE_KEY 			= 'INVALIDATE_KEY';

export const REQUEST_USER_INFO 			= 'REQUEST_USER_INFO';
export const RECEIVE_USER_INFO 			= 'RECEIVE_USER_INFO';
export const REQUEST_USER_INFO_FAIL 	= 'FETCH_USER_FAIL';

export const PROMPT_AUTH 				= 'PROMPT_AUTH';
export const DISMISS_PROMPT_AUTH 		= 'DISMISS_PROMPT_AUTH';